# PySNMP SMI module. Autogenerated from smidump -f python SMART-MIB
# by libsmi2pysnmp-0.1.3 at Tue Nov 12 02:27:44 2013,
# Python version sys.version_info(major=2, minor=7, micro=5, releaselevel='final', serial=0)

# Imports

( Integer32, NotificationType, MibScalar, MibTable, MibTableRow, MibTableColumn, ) = mibBuilder.importSymbols("", "Integer32", "NotificationType", "MibScalar", "MibTable", "MibTableRow", "MibTableColumn")
( Integer, ObjectIdentifier, OctetString, ) = mibBuilder.importSymbols("ASN1", "Integer", "ObjectIdentifier", "OctetString")
( NamedValues, ) = mibBuilder.importSymbols("ASN1-ENUMERATION", "NamedValues")
( ConstraintsIntersection, ConstraintsUnion, SingleValueConstraint, ValueRangeConstraint, ValueSizeConstraint, ) = mibBuilder.importSymbols("ASN1-REFINEMENT", "ConstraintsIntersection", "ConstraintsUnion", "SingleValueConstraint", "ValueRangeConstraint", "ValueSizeConstraint")
( Bits, Integer32, MibIdentifier, TimeTicks, ) = mibBuilder.importSymbols("SNMPv2-SMI", "Bits", "Integer32", "MibIdentifier", "TimeTicks")
( ufrgs, ) = mibBuilder.importSymbols("UFRGS-MIB", "ufrgs")

# Objects

smart = MibIdentifier((0, 0, 12619, 1))
general = MibIdentifier((0, 0, 12619, 1, 1))
info = MibScalar((0, 0, 12619, 1, 1, 1), OctetString().subtype(subtypeSpec=ValueSizeConstraint(255, 255)).setFixedLength(255)).setMaxAccess("readonly")
if mibBuilder.loadTexts: info.setDescription("Informa dados da empresa fornecedora da cancela.")
firmware = MibScalar((0, 0, 12619, 1, 1, 2), OctetString().subtype(subtypeSpec=ValueSizeConstraint(255, 255)).setFixedLength(255)).setMaxAccess("readonly")
if mibBuilder.loadTexts: firmware.setDescription("Versão do firmware instalado na cancela.")
bootDate = MibScalar((0, 0, 12619, 1, 1, 5), OctetString().subtype(subtypeSpec=ValueSizeConstraint(16, 16)).setFixedLength(16)).setMaxAccess("readonly")
if mibBuilder.loadTexts: bootDate.setDescription("Data da última inicialização no formato 'YYYY-MM-DD HH24:MM:SS'")
lastCrashCode = MibScalar((0, 0, 12619, 1, 1, 9), Integer32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: lastCrashCode.setDescription("Código do último erro.")
cards = MibIdentifier((0, 0, 12619, 1, 2))
cardsAcceptedTable = MibTable((0, 0, 12619, 1, 2, 1))
if mibBuilder.loadTexts: cardsAcceptedTable.setDescription("Tabela que contém os tipos de pagamentos aceitos.")
cardsAcceptedEntry = MibTableRow((0, 0, 12619, 1, 2, 1, 1)).setIndexNames((0, "SMART-MIB", "cardID"))
if mibBuilder.loadTexts: cardsAcceptedEntry.setDescription("")
cardID = MibTableColumn((0, 0, 12619, 1, 2, 1, 1, 1), Integer32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: cardID.setDescription("Código do tipo de pagamento.")
cardDescription = MibTableColumn((0, 0, 12619, 1, 2, 1, 1, 2), OctetString().subtype(subtypeSpec=ValueSizeConstraint(0, 255))).setMaxAccess("readonly")
if mibBuilder.loadTexts: cardDescription.setDescription("Descrição do tipo de pagamento.")
stats = MibIdentifier((0, 0, 12619, 1, 3))
hw = MibIdentifier((0, 0, 12619, 1, 4))
inputVoltage = MibScalar((0, 0, 12619, 1, 4, 2), Integer32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: inputVoltage.setDescription("")
motorVoltage = MibScalar((0, 0, 12619, 1, 4, 3), Integer32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: motorVoltage.setDescription("")
network = MibIdentifier((0, 0, 12619, 1, 5))
btPin = MibScalar((0, 0, 12619, 1, 5, 2), OctetString()).setMaxAccess("readwrite")
if mibBuilder.loadTexts: btPin.setDescription("Pin da interface de bluetooth.")
ifCount = MibScalar((0, 0, 12619, 1, 5, 3), Integer32()).setMaxAccess("readwrite")
if mibBuilder.loadTexts: ifCount.setDescription("Numero de interfaces de rede (802.3 e 802.11) existentes.")
ifTable = MibTable((0, 0, 12619, 1, 5, 4))
if mibBuilder.loadTexts: ifTable.setDescription("Tabela contendo informacoes de interfaces de rede.")
ifEntry = MibTableRow((0, 0, 12619, 1, 5, 4, 1)).setIndexNames((0, "SMART-MIB", "ifId"))
if mibBuilder.loadTexts: ifEntry.setDescription("")
ifId = MibTableColumn((0, 0, 12619, 1, 5, 4, 1, 1), Integer32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: ifId.setDescription("Id da interface de rede (wireless  ou ethernet)")
ifType = MibTableColumn((0, 0, 12619, 1, 5, 4, 1, 3), Integer32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: ifType.setDescription("Tipo da interface de rede (wireless  ou ethernet)")

# Augmentions

# Notifications

trapCrash = NotificationType((0, 0, 12619, 1, 0, 1)).setObjects(*(("SMART-MIB", "lastCrashCode"), ) )
if mibBuilder.loadTexts: trapCrash.setDescription("")
trapFirmwareUpdate = NotificationType((0, 0, 12619, 1, 0, 2)).setObjects(*(("SMART-MIB", "firmware"), ) )
if mibBuilder.loadTexts: trapFirmwareUpdate.setDescription("")

# Exports

# Objects
mibBuilder.exportSymbols("SMART-MIB", smart=smart, general=general, info=info, firmware=firmware, bootDate=bootDate, lastCrashCode=lastCrashCode, cards=cards, cardsAcceptedTable=cardsAcceptedTable, cardsAcceptedEntry=cardsAcceptedEntry, cardID=cardID, cardDescription=cardDescription, stats=stats, hw=hw, inputVoltage=inputVoltage, motorVoltage=motorVoltage, network=network, btPin=btPin, ifCount=ifCount, ifTable=ifTable, ifEntry=ifEntry, ifId=ifId, ifType=ifType)

# Notifications
mibBuilder.exportSymbols("SMART-MIB", trapCrash=trapCrash, trapFirmwareUpdate=trapFirmwareUpdate)

