
SMART-MIB DEFINITIONS ::= BEGIN

IMPORTS
	enterprises, Gauge, IpAddress, 
	Counter
		FROM RFC1155-SMI
	OBJECT-TYPE
		FROM RFC-1212
	ufrgs
		FROM UFRGS-MIB;

smart           OBJECT IDENTIFIER ::= { ufrgs 1 }

fsFilesSent  OBJECT-TYPE
	SYNTAX     Counter
	ACCESS     read-only
	STATUS     mandatory
	DESCRIPTION 
		"Arquivos enviados."
	::= { smart 1 }

fsRemoteServer  OBJECT-TYPE
	SYNTAX     IpAddress
	ACCESS     read-write
	STATUS     mandatory
	DESCRIPTION 
		"Endereço do servidor remoto."
	::= { smart 2 }

fsRemoteServerPort  OBJECT-TYPE
	SYNTAX     Gauge
	ACCESS     read-write
	STATUS     mandatory
	DESCRIPTION 
		"Porta do servidor remoto."
	::= { smart 3 }

fsLocalServerPort  OBJECT-TYPE
	SYNTAX     Gauge
	ACCESS     read-write
	STATUS     mandatory
	DESCRIPTION 
		"Porta do servidor local."
	::= { smart 4 }
END


-- This MIB was created using NuDesign Technologies' Visual MIBuilder (Ver 5.2).

